version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev 
    image: baps:dev
    ports:
      - "8000:8000"
    volumes:
      - ~/.ssh:/root/.ssh/
      - ~/.aws/credentials:/root/.aws/credentials
      - .:/zda/dev/
    depends_on:
      - postgres
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: bapspsw
    ports:
      - "5432:5432"
    volumes:
      - baps-pg:/var/lib/postgresql/data

volumes:
  baps-pg:
    external: true
